// Relora i18n — 9 languages
(function () {
  'use strict';

  var LANGS = {
    ja: '日本語', en: 'English', zh: '中文', ko: '한국어',
    de: 'Deutsch', fr: 'Français', it: 'Italiano', es: 'Español', pt: 'Português'
  };

  var T = {
    // ── INDEX ──
    ja: {
      "meta.title": "Relora — 恋愛メッセージ分析AI",
      "meta.description": "ReloraはチャットのスクリーンショットをAIが分析し、相手の心理・温度感・返信候補を提案する恋愛相談アプリです。すべてオンデバイスで完結し、プライバシーを完全に保護します。",
      "nav.features": "機能",
      "nav.how": "使い方",
      "nav.privacy": "プライバシー",
      "nav.pricing": "料金",
      "nav.cta": "App Storeで入手",
      "hero.badge": "完全オンデバイスAI",
      "hero.title_html": '恋愛メッセージを<br><span>AIが読み解く</span>',
      "hero.desc": "チャットのスクリーンショットを投入するだけ。相手の心理・温度感・最適な返信を、あなたのデバイス上で分析します。",
      "hero.cta_primary": "App Storeでダウンロード",
      "hero.cta_secondary": "使い方を見る",
      "features.label": "Features",
      "features.title": "あなたの恋愛を、構造化する",
      "features.desc": "ただの返信生成ではありません。会話の裏にある心理・リスク・戦略を分析し、あなたの判断をサポートします。",
      "features.psychology.title": "心理分析",
      "features.psychology.desc": "相手のメッセージの表面的な意味だけでなく、裏にある意図や感情を読み解きます。",
      "features.temperature.title": "温度感スコア",
      "features.temperature.desc": "相手の関心度を1〜10のスコアで可視化。感覚ではなくデータで判断できます。",
      "features.reply.title": "返信候補3パターン",
      "features.reply.desc": "「攻め」「守り」「様子見」の3種類の返信を、理由付きで提案します。",
      "features.risk.title": "リスク警告",
      "features.risk.desc": "「追撃NG」「既読スルーを責めない」など、関係を悪化させる行動を事前に警告します。",
      "features.screenshot.title": "スクリーンショット対応",
      "features.screenshot.desc": "LINE、Instagram、Tinder、WhatsApp — どのアプリのスクショでも分析可能です。",
      "features.private.title": "完全プライベート",
      "features.private.desc": "すべてのAI処理はデバイス上で完結。あなたの会話データは一切外部に送信されません。",
      "how.label": "How it works",
      "how.title": "3ステップで分析完了",
      "how.desc": "直感的な操作で、数秒のうちに深い洞察を得られます。",
      "how.step1.title": "スクショを撮る",
      "how.step1.desc": "気になるチャットのスクリーンショットを撮影。複数枚まとめてOK。",
      "how.step2.title": "状況を選ぶ",
      "how.step2.desc": "関係性・目的・状況をプルダウンで選択。テキストで補足も可能。",
      "how.step3.title": "AIが分析",
      "how.step3.desc": "心理分析・温度感・返信候補・NG行動を構造化して表示。すべてデバイス上で処理。",
      "privacy_section.title": "あなたのデータは、あなたのもの",
      "privacy_section.desc": "Reloraはサーバーを一切使いません。すべてのAI処理がiPhone上で完結する、完全ローカル設計です。",
      "privacy_section.ondevice.title": "オンデバイスAI",
      "privacy_section.ondevice.desc": "AI処理はすべてあなたのiPhone上で実行",
      "privacy_section.nodata.title": "データ送信なし",
      "privacy_section.nodata.desc": "スクショや会話データは外部サーバーに送信されません",
      "privacy_section.delete.title": "完全削除可能",
      "privacy_section.delete.desc": "アプリを削除すればすべてのデータが消えます",
      "pricing.label": "Pricing",
      "pricing.title": "シンプルな料金プラン",
      "pricing.desc": "まずは無料でお試しください。",
      "pricing.free.name": "無料プラン",
      "pricing.free.price": "¥0",
      "pricing.free.f1": "1日3回まで分析",
      "pricing.free.f2": "基本的な心理分析",
      "pricing.free.f3": "返信候補の提案",
      "pricing.free.f4": "完全プライバシー保護",
      "pricing.free.cta": "無料で始める",
      "pricing.premium.badge": "おすすめ",
      "pricing.premium.name": "プレミアム",
      "pricing.premium.price_html": '¥980<span>/月</span>',
      "pricing.premium.f1": "無制限の分析",
      "pricing.premium.f2": "深い心理分析・戦略提案",
      "pricing.premium.f3": "相手ごとの記憶・パーソナライズ",
      "pricing.premium.f4": "履歴活用・傾向分析",
      "pricing.premium.f5": "完全プライバシー保護",
      "pricing.premium.cta": "プレミアムを始める",
      "cta.title": "恋愛の悩み、AIと一緒に考えよう",
      "cta.desc": "Reloraがあなたの判断をサポートします。",
      "cta.button": "App Storeでダウンロード",
      "footer.privacy": "プライバシーポリシー",
      "footer.terms": "利用規約",
      "footer.contact": "お問い合わせ",
      // privacy page
      "privacy.meta.title": "プライバシーポリシー — Relora",
      "privacy.title": "プライバシーポリシー",
      "privacy.date": "最終更新日: 2026年4月5日",
      "privacy.intro": "Relora（以下「本アプリ」）は、ユーザーのプライバシーを最優先に設計されています。本ポリシーは、本アプリにおける情報の取り扱いについて説明します。",
      "privacy.h1": "1. 基本方針",
      "privacy.p1": "本アプリは完全オンデバイスで動作します。ユーザーのデータを外部サーバーに送信することは一切ありません。すべてのAI処理はユーザーのデバイス上で実行されます。",
      "privacy.h2": "2. 取り扱う情報",
      "privacy.p2": "本アプリがデバイス上で処理する情報は以下の通りです。これらはすべてユーザーのデバイス内にのみ保存されます。",
      "privacy.p2.li1": "ユーザーが入力したスクリーンショット画像",
      "privacy.p2.li2": "ユーザーが入力したテキスト情報（補足メモ等）",
      "privacy.p2.li3": "AI分析結果",
      "privacy.p2.li4": "アプリ内課金に関する情報（Apple経由で処理）",
      "privacy.h3": "3. 情報の利用目的",
      "privacy.p3": "上記の情報は、オンデバイスでのAI分析処理のみに使用されます。",
      "privacy.h4": "4. 第三者への提供",
      "privacy.p4": "本アプリはユーザーの情報を第三者に提供しません。外部サーバーへのデータ送信は一切行いません。",
      "privacy.h5": "5. データの保管",
      "privacy.p5": "すべてのデータはユーザーのデバイス内にのみ保存されます。クラウドへのバックアップは行いません。",
      "privacy.h6": "6. データの削除",
      "privacy.p6": "アプリを削除することで、本アプリに関連するすべてのデータが削除されます。また、アプリ内の設定からデータを個別に削除することも可能です。",
      "privacy.h7": "7. App Store プライバシー",
      "privacy.p7.li1": "Data Not Collected: 本アプリはユーザーデータを収集しません",
      "privacy.p7.li2": "Data Not Linked to You: データはユーザーに紐付けられません",
      "privacy.h8": "8. お子様のプライバシー",
      "privacy.p8": "本アプリは17歳以上を対象としています。17歳未満のお子様からの情報を意図的に収集することはありません。",
      "privacy.h9": "9. ポリシーの変更",
      "privacy.p9": "本ポリシーは予告なく変更される場合があります。変更がある場合は、本ページにて更新いたします。",
      "privacy.h10": "10. お問い合わせ",
      "privacy.p10": "プライバシーに関するお問い合わせは、以下までご連絡ください。",
      "privacy.nav.home": "ホーム",
      "privacy.nav.terms": "利用規約",
      // terms page
      "terms.meta.title": "利用規約 — Relora",
      "terms.title": "利用規約",
      "terms.date": "最終更新日: 2026年4月5日",
      "terms.intro": "本利用規約（以下「本規約」）は、Relora（以下「本アプリ」）の利用条件を定めるものです。本アプリをご利用になる前に、本規約をよくお読みください。",
      "terms.h1": "1. サービスの内容",
      "terms.p1a": "本アプリは、チャットのスクリーンショットをAIで分析し、会話の心理分析・返信候補の提案等を行う参考情報提供サービスです。",
      "terms.p1b": "本アプリが提供する情報は、AIによる一般的な傾向に基づく参考情報であり、専門的なカウンセリングやアドバイスではありません。",
      "terms.h2": "2. 免責事項",
      "terms.p2.li1": "本アプリの分析結果の正確性、完全性、有用性について保証するものではありません",
      "terms.p2.li2": "本アプリの利用に基づくいかなる行動の結果についても、開発者は責任を負いません",
      "terms.p2.li3": "メッセージの送信や行動に関する最終判断は、ユーザー自身の責任において行ってください",
      "terms.p2.li4": "本アプリは恋愛や人間関係に関する専門的なカウンセリングの代替ではありません",
      "terms.h3": "3. 利用条件",
      "terms.p3.li1": "本アプリは17歳以上の方を対象としています",
      "terms.p3.li2": "本アプリを違法な目的で使用してはなりません",
      "terms.p3.li3": "ストーカー行為、ハラスメント、その他他者を害する目的での使用は禁止します",
      "terms.h4": "4. 課金について",
      "terms.p4.li1": "本アプリはApp内課金（サブスクリプション）を提供しています",
      "terms.p4.li2": "課金はApple Inc.を通じて処理されます",
      "terms.p4.li3": "サブスクリプションは自動更新されます。更新日の24時間前までにキャンセルしない限り、自動的に更新されます",
      "terms.p4.li4": "サブスクリプションの管理およびキャンセルは、iOSの設定アプリから行えます",
      "terms.h5": "5. 知的財産権",
      "terms.p5": "本アプリのデザイン、コード、コンテンツに関する知的財産権は開発者に帰属します。",
      "terms.h6": "6. サービスの変更・終了",
      "terms.p6": "開発者は、事前の通知なく本アプリの機能を変更、または本サービスを終了する権利を有します。",
      "terms.h7": "7. 規約の変更",
      "terms.p7": "本規約は予告なく変更される場合があります。変更後の規約は、本ページへの掲載をもって効力を生じます。",
      "terms.h8": "8. 準拠法・管轄裁判所",
      "terms.p8": "本規約は日本法に準拠します。本規約に関する紛争については、東京地方裁判所を第一審の専属的合意管轄裁判所とします。",
      "terms.h9": "9. お問い合わせ",
      "terms.p9": "本規約に関するお問い合わせは、以下までご連絡ください。",
      "terms.nav.home": "ホーム",
      "terms.nav.privacy": "プライバシーポリシー"
    },
    en: {
      "meta.title": "Relora — AI Romance Message Analyzer",
      "meta.description": "Relora uses AI to analyze your chat screenshots and reveal the psychology, interest level, and best replies for your love life. Everything runs on-device, keeping your privacy fully protected.",
      "nav.features": "Features",
      "nav.how": "How It Works",
      "nav.privacy": "Privacy",
      "nav.pricing": "Pricing",
      "nav.cta": "Get on App Store",
      "hero.badge": "100% On-Device AI",
      "hero.title_html": 'AI Decodes Your<br><span>Love Messages</span>',
      "hero.desc": "Just drop in a chat screenshot. Relora reads the psychology, gauges their interest, and suggests the perfect reply — all on your device.",
      "hero.cta_primary": "Download on App Store",
      "hero.cta_secondary": "See How It Works",
      "features.label": "Features",
      "features.title": "Bring clarity to your love life",
      "features.desc": "More than just reply suggestions. Relora uncovers the psychology, risks, and strategy behind every conversation to help you make smarter decisions.",
      "features.psychology.title": "Psychology Analysis",
      "features.psychology.desc": "Go beyond the surface. Understand the real intent and emotion behind every message.",
      "features.temperature.title": "Interest Score",
      "features.temperature.desc": "See their level of interest as a score from 1 to 10. Make decisions based on data, not gut feelings.",
      "features.reply.title": "3 Reply Options",
      "features.reply.desc": "Get three tailored replies — bold, safe, and wait-and-see — each with a clear explanation.",
      "features.risk.title": "Risk Warnings",
      "features.risk.desc": "Avoid mistakes before you make them. Relora flags actions that could damage your connection.",
      "features.screenshot.title": "Any App, Any Screenshot",
      "features.screenshot.desc": "LINE, Instagram, Tinder, WhatsApp — analyze screenshots from any messaging app.",
      "features.private.title": "Completely Private",
      "features.private.desc": "All AI processing happens on your device. Your conversations are never sent anywhere.",
      "how.label": "How it works",
      "how.title": "3 Steps to Deep Insight",
      "how.desc": "Simple, intuitive, and done in seconds.",
      "how.step1.title": "Take a Screenshot",
      "how.step1.desc": "Capture the chat you want to analyze. Multiple screenshots are fine.",
      "how.step2.title": "Set the Context",
      "how.step2.desc": "Choose your relationship type, goal, and situation from a dropdown. Add notes if needed.",
      "how.step3.title": "AI Analyzes",
      "how.step3.desc": "Get a structured breakdown of psychology, interest level, reply options, and risks — all on your device.",
      "privacy_section.title": "Your Data Stays Yours",
      "privacy_section.desc": "Relora uses no servers. Every AI process runs entirely on your iPhone — a fully local design.",
      "privacy_section.ondevice.title": "On-Device AI",
      "privacy_section.ondevice.desc": "All AI processing runs on your iPhone",
      "privacy_section.nodata.title": "No Data Transmission",
      "privacy_section.nodata.desc": "Screenshots and chats are never sent to external servers",
      "privacy_section.delete.title": "Delete Everything",
      "privacy_section.delete.desc": "Uninstall the app and all your data is gone",
      "pricing.label": "Pricing",
      "pricing.title": "Simple, Honest Pricing",
      "pricing.desc": "Start for free. Upgrade when you're ready.",
      "pricing.free.name": "Free",
      "pricing.free.price": "¥0",
      "pricing.free.f1": "3 analyses per day",
      "pricing.free.f2": "Core psychology analysis",
      "pricing.free.f3": "Reply suggestions",
      "pricing.free.f4": "Full privacy protection",
      "pricing.free.cta": "Get Started Free",
      "pricing.premium.badge": "Recommended",
      "pricing.premium.name": "Premium",
      "pricing.premium.price_html": '¥980<span>/mo</span>',
      "pricing.premium.f1": "Unlimited analyses",
      "pricing.premium.f2": "Deep psychology & strategy insights",
      "pricing.premium.f3": "Per-person memory & personalization",
      "pricing.premium.f4": "History & trend analysis",
      "pricing.premium.f5": "Full privacy protection",
      "pricing.premium.cta": "Go Premium",
      "cta.title": "Let AI Help You Navigate Love",
      "cta.desc": "Relora is here to support your decisions.",
      "cta.button": "Download on App Store",
      "footer.privacy": "Privacy Policy",
      "footer.terms": "Terms of Service",
      "footer.contact": "Contact",
      "privacy.meta.title": "Privacy Policy — Relora",
      "privacy.title": "Privacy Policy",
      "privacy.date": "Last updated: April 5, 2026",
      "privacy.intro": "Relora (the \"App\") is designed with your privacy as the top priority. This policy describes how information is handled within the App.",
      "privacy.h1": "1. Core Principles",
      "privacy.p1": "The App operates entirely on-device. Your data is never transmitted to any external server. All AI processing is performed on your device.",
      "privacy.h2": "2. Information Processed",
      "privacy.p2": "The following information may be processed by the App on your device. All of it is stored exclusively on your device.",
      "privacy.p2.li1": "Screenshot images you provide",
      "privacy.p2.li2": "Text information you enter (supplementary notes, etc.)",
      "privacy.p2.li3": "AI analysis results",
      "privacy.p2.li4": "In-app purchase information (processed via Apple)",
      "privacy.h3": "3. Purpose of Use",
      "privacy.p3": "The above information is used solely for on-device AI analysis processing.",
      "privacy.h4": "4. Disclosure to Third Parties",
      "privacy.p4": "The App does not share your information with any third parties. No data is transmitted to external servers.",
      "privacy.h5": "5. Data Storage",
      "privacy.p5": "All data is stored exclusively on your device. No cloud backup is performed.",
      "privacy.h6": "6. Data Deletion",
      "privacy.p6": "Deleting the App removes all data associated with it. You may also delete individual data items from within the App's settings.",
      "privacy.h7": "7. App Store Privacy",
      "privacy.p7.li1": "Data Not Collected: This app does not collect any user data",
      "privacy.p7.li2": "Data Not Linked to You: No data is linked to your identity",
      "privacy.h8": "8. Children's Privacy",
      "privacy.p8": "The App is intended for users aged 17 and older. We do not knowingly collect information from children under the age of 17.",
      "privacy.h9": "9. Policy Changes",
      "privacy.p9": "This policy may be updated without prior notice. Any changes will be reflected on this page.",
      "privacy.h10": "10. Contact",
      "privacy.p10": "For privacy-related inquiries, please contact us at the address below.",
      "privacy.nav.home": "Home",
      "privacy.nav.terms": "Terms of Use",
      "terms.meta.title": "Terms of Service — Relora",
      "terms.title": "Terms of Service",
      "terms.date": "Last updated: April 5, 2026",
      "terms.intro": "These Terms of Service (the \"Terms\") govern your use of Relora (the \"App\"). Please read these Terms carefully before using the App.",
      "terms.h1": "1. Description of Service",
      "terms.p1a": "The App is a reference information service that uses AI to analyze chat screenshots and provides psychological analysis of conversations and suggested replies.",
      "terms.p1b": "The information provided by the App is for general reference purposes based on AI-identified trends and does not constitute professional counseling or advice.",
      "terms.h2": "2. Disclaimer",
      "terms.p2.li1": "We make no guarantees regarding the accuracy, completeness, or usefulness of the App's analysis results",
      "terms.p2.li2": "The developer assumes no responsibility for the consequences of any actions taken based on use of the App",
      "terms.p2.li3": "All final decisions regarding messages sent or actions taken are the sole responsibility of the user",
      "terms.p2.li4": "The App is not a substitute for professional counseling regarding romantic relationships or interpersonal matters",
      "terms.h3": "3. Conditions of Use",
      "terms.p3.li1": "The App is intended for users aged 17 and older",
      "terms.p3.li2": "The App must not be used for any unlawful purpose",
      "terms.p3.li3": "Use for the purpose of stalking, harassment, or otherwise harming others is strictly prohibited",
      "terms.h4": "4. Billing",
      "terms.p4.li1": "The App offers in-app purchases (subscriptions)",
      "terms.p4.li2": "Payments are processed through Apple Inc.",
      "terms.p4.li3": "Subscriptions renew automatically. Unless cancelled at least 24 hours before the renewal date, the subscription will automatically renew",
      "terms.p4.li4": "Subscriptions can be managed and cancelled through the iOS Settings app",
      "terms.h5": "5. Intellectual Property",
      "terms.p5": "All intellectual property rights in the App's design, code, and content belong to the developer.",
      "terms.h6": "6. Modification and Termination of Service",
      "terms.p6": "The developer reserves the right to modify the App's features or terminate the service at any time without prior notice.",
      "terms.h7": "7. Changes to These Terms",
      "terms.p7": "These Terms may be updated without notice. Revised Terms take effect upon publication on this page.",
      "terms.h8": "8. Governing Law and Jurisdiction",
      "terms.p8": "These Terms are governed by the laws of Japan. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the Tokyo District Court as the court of first instance.",
      "terms.h9": "9. Contact",
      "terms.p9": "For inquiries regarding these Terms, please contact us at the address below.",
      "terms.nav.home": "Home",
      "terms.nav.privacy": "Privacy Policy"
    },
    zh: {
      "meta.title": "Relora — AI 恋爱消息分析",
      "meta.description": "Relora 利用 AI 分析聊天截图，解读对方的心理、好感度与最佳回复策略。所有处理均在设备本地完成，完全保护您的隐私。",
      "nav.features": "功能",
      "nav.how": "使用方法",
      "nav.privacy": "隐私",
      "nav.pricing": "价格",
      "nav.cta": "在 App Store 获取",
      "hero.badge": "完全本地 AI",
      "hero.title_html": 'AI 帮你读懂<br><span>恋爱中的每条消息</span>',
      "hero.desc": "只需上传聊天截图，Relora 即可分析对方心理、好感温度与最佳回复——全程在您的设备上完成。",
      "hero.cta_primary": "在 App Store 下载",
      "hero.cta_secondary": "查看使用方法",
      "features.label": "Features",
      "features.title": "让恋爱变得清晰可见",
      "features.desc": "不只是生成回复。Relora 深入分析对话背后的心理、风险与策略，帮您做出更明智的判断。",
      "features.psychology.title": "心理分析",
      "features.psychology.desc": "不只看表面文字，深入解读对方消息背后的真实意图与情感。",
      "features.temperature.title": "好感度评分",
      "features.temperature.desc": "以 1〜10 分量化对方的兴趣程度，用数据代替感觉做判断。",
      "features.reply.title": "3 种回复方案",
      "features.reply.desc": "提供「主动进攻」「稳妥保守」「静观其变」三种回复，并附上理由说明。",
      "features.risk.title": "风险预警",
      "features.risk.desc": "提前警示可能让关系变糟的行为，例如「不要连续追问」或「不要责备已读不回」。",
      "features.screenshot.title": "支持任意截图",
      "features.screenshot.desc": "微信、Instagram、Tinder、WhatsApp——任何应用的截图均可分析。",
      "features.private.title": "完全私密",
      "features.private.desc": "所有 AI 处理均在设备本地完成，您的聊天数据绝不外传。",
      "how.label": "How it works",
      "how.title": "三步完成深度分析",
      "how.desc": "操作直观简单，数秒内获得深刻洞察。",
      "how.step1.title": "截取聊天截图",
      "how.step1.desc": "截取您想分析的聊天内容，支持多张截图同时上传。",
      "how.step2.title": "设定情境",
      "how.step2.desc": "从下拉菜单中选择关系类型、目标与当前情况，也可文字补充说明。",
      "how.step3.title": "AI 深度分析",
      "how.step3.desc": "结构化呈现心理分析、好感评分、回复建议与风险提示——全部在设备上处理。",
      "privacy_section.title": "您的数据，只属于您",
      "privacy_section.desc": "Relora 完全不使用服务器。所有 AI 处理均在您的 iPhone 上本地完成。",
      "privacy_section.ondevice.title": "本地 AI 处理",
      "privacy_section.ondevice.desc": "所有 AI 运算均在您的 iPhone 上执行",
      "privacy_section.nodata.title": "零数据传输",
      "privacy_section.nodata.desc": "截图与聊天内容绝不发送至外部服务器",
      "privacy_section.delete.title": "可完全删除",
      "privacy_section.delete.desc": "卸载应用后，所有数据将彻底清除",
      "pricing.label": "Pricing",
      "pricing.title": "简单透明的定价",
      "pricing.desc": "免费体验，随时升级。",
      "pricing.free.name": "免费版",
      "pricing.free.price": "¥0",
      "pricing.free.f1": "每日最多 3 次分析",
      "pricing.free.f2": "基础心理分析",
      "pricing.free.f3": "回复建议",
      "pricing.free.f4": "完全隐私保护",
      "pricing.free.cta": "免费开始",
      "pricing.premium.badge": "推荐",
      "pricing.premium.name": "高级版",
      "pricing.premium.price_html": '¥980<span>/月</span>',
      "pricing.premium.f1": "无限次分析",
      "pricing.premium.f2": "深度心理分析与策略建议",
      "pricing.premium.f3": "按对象记忆与个性化",
      "pricing.premium.f4": "历史记录与趋势分析",
      "pricing.premium.f5": "完全隐私保护",
      "pricing.premium.cta": "升级高级版",
      "cta.title": "恋爱的烦恼，让 AI 陪你一起想",
      "cta.desc": "Relora 助您做出更好的决定。",
      "cta.button": "在 App Store 下载",
      "footer.privacy": "隐私政策",
      "footer.terms": "服务条款",
      "footer.contact": "联系我们",
      "privacy.meta.title": "隐私政策 — Relora",
      "privacy.title": "隐私政策",
      "privacy.date": "最后更新日期：2026年4月5日",
      "privacy.intro": "Relora（以下简称「本应用」）以保护用户隐私为首要设计原则。本政策说明本应用对信息的处理方式。",
      "privacy.h1": "1. 基本方针",
      "privacy.p1": "本应用完全在设备本地运行。用户数据绝不会传输至任何外部服务器。所有AI处理均在用户设备上执行。",
      "privacy.h2": "2. 处理的信息",
      "privacy.p2": "以下为本应用在设备上处理的信息。所有信息均仅存储于用户设备内。",
      "privacy.p2.li1": "用户提供的截图图像",
      "privacy.p2.li2": "用户输入的文字信息（补充备注等）",
      "privacy.p2.li3": "AI分析结果",
      "privacy.p2.li4": "应用内购买信息（通过Apple处理）",
      "privacy.h3": "3. 信息使用目的",
      "privacy.p3": "上述信息仅用于设备本地的AI分析处理。",
      "privacy.h4": "4. 向第三方披露",
      "privacy.p4": "本应用不会向任何第三方提供用户信息。不会向外部服务器传输任何数据。",
      "privacy.h5": "5. 数据存储",
      "privacy.p5": "所有数据均仅存储于用户设备内。不进行云端备份。",
      "privacy.h6": "6. 数据删除",
      "privacy.p6": "删除本应用后，与本应用相关的所有数据将被删除。您也可以在应用内设置中单独删除特定数据。",
      "privacy.h7": "7. App Store 隐私",
      "privacy.p7.li1": "Data Not Collected：本应用不收集任何用户数据",
      "privacy.p7.li2": "Data Not Linked to You：数据不与您的身份关联",
      "privacy.h8": "8. 儿童隐私",
      "privacy.p8": "本应用面向17岁及以上用户。我们不会故意收集17岁以下未成年人的信息。",
      "privacy.h9": "9. 政策变更",
      "privacy.p9": "本政策可能在不事先通知的情况下进行修订。如有变更，将在本页面上予以更新。",
      "privacy.h10": "10. 联系方式",
      "privacy.p10": "如有隐私相关问题，请通过以下方式与我们联系。",
      "privacy.nav.home": "首页",
      "privacy.nav.terms": "使用条款",
      "terms.meta.title": "使用条款 — Relora",
      "terms.title": "使用条款",
      "terms.date": "最后更新日期：2026年4月5日",
      "terms.intro": "本使用条款（以下简称「本条款」）规定了使用Relora（以下简称「本应用」）的条件。请在使用本应用前仔细阅读本条款。",
      "terms.h1": "1. 服务内容",
      "terms.p1a": "本应用是一项参考信息服务，利用人工智能分析聊天截图，提供对话心理分析及回复建议等功能。",
      "terms.p1b": "本应用提供的信息仅为基于人工智能识别的一般趋势的参考信息，不构成专业咨询或建议。",
      "terms.h2": "2. 免责声明",
      "terms.p2.li1": "本应用不对分析结果的准确性、完整性或实用性作出任何保证",
      "terms.p2.li2": "对于因使用本应用而采取任何行动所产生的后果，开发者概不负责",
      "terms.p2.li3": "关于发送消息或采取行动的最终决定，由用户自行承担责任",
      "terms.p2.li4": "本应用不能替代针对恋爱关系或人际关系的专业咨询",
      "terms.h3": "3. 使用条件",
      "terms.p3.li1": "本应用适用于17岁及以上的用户",
      "terms.p3.li2": "严禁将本应用用于任何违法目的",
      "terms.p3.li3": "严禁将本应用用于跟踪骚扰、骚扰他人或以其他方式伤害他人",
      "terms.h4": "4. 付费说明",
      "terms.p4.li1": "本应用提供应用内购买（订阅）服务",
      "terms.p4.li2": "付款通过Apple Inc.处理",
      "terms.p4.li3": "订阅将自动续订。除非在续订日期前至少24小时取消，否则订阅将自动续订",
      "terms.p4.li4": "可通过iOS设置应用管理和取消订阅",
      "terms.h5": "5. 知识产权",
      "terms.p5": "本应用的设计、代码及内容相关的知识产权归开发者所有。",
      "terms.h6": "6. 服务变更与终止",
      "terms.p6": "开发者保留在不事先通知的情况下修改本应用功能或终止本服务的权利。",
      "terms.h7": "7. 条款变更",
      "terms.p7": "本条款可能在不另行通知的情况下进行修改。修订后的条款自在本页面发布之时起生效。",
      "terms.h8": "8. 准据法与管辖法院",
      "terms.p8": "本条款受日本法律管辖。因本条款引起的任何争议，以东京地方法院为第一审专属合意管辖法院。",
      "terms.h9": "9. 联系我们",
      "terms.p9": "如对本条款有任何疑问，请通过以下方式与我们联系。",
      "terms.nav.home": "首页",
      "terms.nav.privacy": "隐私政策"
    },
    ko: {
      "meta.title": "Relora — AI 연애 메시지 분석",
      "meta.description": "Relora는 채팅 스크린샷을 AI로 분석해 상대방의 심리·호감도·최적 답장을 제안하는 연애 상담 앱입니다. 모든 처리는 기기 내에서 완결되어 프라이버시를 완벽하게 보호합니다.",
      "nav.features": "기능",
      "nav.how": "사용법",
      "nav.privacy": "개인정보",
      "nav.pricing": "요금",
      "nav.cta": "App Store에서 받기",
      "hero.badge": "완전 온디바이스 AI",
      "hero.title_html": '연애 메시지,<br><span>AI가 속속들이 읽어드립니다</span>',
      "hero.desc": "채팅 스크린샷만 올리면 끝. 상대의 심리·호감도·최적 답장을 내 기기에서 바로 분석합니다.",
      "hero.cta_primary": "App Store에서 다운로드",
      "hero.cta_secondary": "사용법 보기",
      "features.label": "Features",
      "features.title": "연애를 데이터로 정리하다",
      "features.desc": "단순한 답장 생성이 아닙니다. 대화 뒤에 숨은 심리·리스크·전략을 분석해 더 나은 판단을 도와드립니다.",
      "features.psychology.title": "심리 분석",
      "features.psychology.desc": "메시지의 표면적 의미를 넘어, 상대방의 진짜 의도와 감정을 읽어냅니다.",
      "features.temperature.title": "호감도 점수",
      "features.temperature.desc": "상대의 관심도를 1~10점으로 수치화. 느낌이 아닌 데이터로 판단하세요.",
      "features.reply.title": "답장 후보 3가지",
      "features.reply.desc": "「적극적」「안전」「관망」세 가지 답장을 이유와 함께 제안합니다.",
      "features.risk.title": "리스크 경고",
      "features.risk.desc": "\"연속 메시지 금지\", \"읽씹 추궁 금지\" 등 관계를 악화시킬 행동을 미리 경고합니다.",
      "features.screenshot.title": "어떤 앱이든 OK",
      "features.screenshot.desc": "카카오톡, Instagram, Tinder, WhatsApp — 모든 메신저 스크린샷 분석 가능.",
      "features.private.title": "완전 프라이빗",
      "features.private.desc": "모든 AI 처리는 기기 내에서 완결. 대화 데이터는 외부로 절대 전송되지 않습니다.",
      "how.label": "How it works",
      "how.title": "3단계로 분석 완료",
      "how.desc": "직관적인 조작으로 몇 초 만에 깊은 인사이트를 얻으세요.",
      "how.step1.title": "스크린샷 찍기",
      "how.step1.desc": "궁금한 채팅의 스크린샷을 찍으세요. 여러 장도 한꺼번에 OK.",
      "how.step2.title": "상황 선택",
      "how.step2.desc": "관계·목적·상황을 드롭다운으로 선택. 텍스트로 추가 설명도 가능.",
      "how.step3.title": "AI 분석",
      "how.step3.desc": "심리 분석·호감도·답장 후보·NG 행동을 구조화해서 표시. 모두 기기 내 처리.",
      "privacy_section.title": "내 데이터는 내 것",
      "privacy_section.desc": "Relora는 서버를 일절 사용하지 않습니다. 모든 AI 처리가 iPhone에서 완결되는 완전 로컬 설계입니다.",
      "privacy_section.ondevice.title": "온디바이스 AI",
      "privacy_section.ondevice.desc": "모든 AI 처리는 내 iPhone에서 실행",
      "privacy_section.nodata.title": "데이터 전송 없음",
      "privacy_section.nodata.desc": "스크린샷·대화 데이터는 외부 서버로 전송되지 않음",
      "privacy_section.delete.title": "완전 삭제 가능",
      "privacy_section.delete.desc": "앱을 삭제하면 모든 데이터가 완전히 사라집니다",
      "pricing.label": "Pricing",
      "pricing.title": "심플한 요금제",
      "pricing.desc": "먼저 무료로 체험해 보세요.",
      "pricing.free.name": "무료 플랜",
      "pricing.free.price": "¥0",
      "pricing.free.f1": "하루 3회 분석",
      "pricing.free.f2": "기본 심리 분석",
      "pricing.free.f3": "답장 후보 제안",
      "pricing.free.f4": "완전 프라이버시 보호",
      "pricing.free.cta": "무료로 시작하기",
      "pricing.premium.badge": "추천",
      "pricing.premium.name": "프리미엄",
      "pricing.premium.price_html": '¥980<span>/월</span>',
      "pricing.premium.f1": "무제한 분석",
      "pricing.premium.f2": "심층 심리 분석·전략 제안",
      "pricing.premium.f3": "상대별 기억·개인화",
      "pricing.premium.f4": "기록 활용·경향 분석",
      "pricing.premium.f5": "완전 프라이버시 보호",
      "pricing.premium.cta": "프리미엄 시작하기",
      "cta.title": "연애 고민, AI와 함께 풀어보세요",
      "cta.desc": "Relora가 당신의 판단을 도와드립니다.",
      "cta.button": "App Store에서 다운로드",
      "footer.privacy": "개인정보처리방침",
      "footer.terms": "이용약관",
      "footer.contact": "문의하기",
      "privacy.meta.title": "개인정보 처리방침 — Relora",
      "privacy.title": "개인정보 처리방침",
      "privacy.date": "최종 업데이트: 2026년 4월 5일",
      "privacy.intro": "Relora(이하 '본 앱')는 사용자의 개인정보 보호를 최우선으로 설계되었습니다. 본 방침은 본 앱에서의 정보 처리 방식에 대해 설명합니다.",
      "privacy.h1": "1. 기본 원칙",
      "privacy.p1": "본 앱은 완전히 온디바이스로 작동합니다. 사용자 데이터는 외부 서버로 전송되지 않습니다. 모든 AI 처리는 사용자의 기기에서 실행됩니다.",
      "privacy.h2": "2. 처리하는 정보",
      "privacy.p2": "본 앱이 기기에서 처리하는 정보는 다음과 같습니다. 이 모든 정보는 사용자의 기기 내에만 저장됩니다.",
      "privacy.p2.li1": "사용자가 제공한 스크린샷 이미지",
      "privacy.p2.li2": "사용자가 입력한 텍스트 정보(보충 메모 등)",
      "privacy.p2.li3": "AI 분석 결과",
      "privacy.p2.li4": "인앱 결제 정보(Apple을 통해 처리)",
      "privacy.h3": "3. 정보의 이용 목적",
      "privacy.p3": "위의 정보는 온디바이스 AI 분석 처리에만 사용됩니다.",
      "privacy.h4": "4. 제3자 제공",
      "privacy.p4": "본 앱은 사용자의 정보를 제3자에게 제공하지 않습니다. 외부 서버로의 데이터 전송은 일절 행하지 않습니다.",
      "privacy.h5": "5. 데이터 보관",
      "privacy.p5": "모든 데이터는 사용자의 기기 내에만 저장됩니다. 클라우드 백업은 수행하지 않습니다.",
      "privacy.h6": "6. 데이터 삭제",
      "privacy.p6": "앱을 삭제하면 본 앱과 관련된 모든 데이터가 삭제됩니다. 또한 앱 내 설정에서 개별 데이터를 삭제하는 것도 가능합니다.",
      "privacy.h7": "7. App Store 개인정보",
      "privacy.p7.li1": "Data Not Collected: 본 앱은 사용자 데이터를 수집하지 않습니다",
      "privacy.p7.li2": "Data Not Linked to You: 데이터는 사용자와 연결되지 않습니다",
      "privacy.h8": "8. 아동 개인정보",
      "privacy.p8": "본 앱은 만 17세 이상을 대상으로 합니다. 만 17세 미만 아동의 정보를 의도적으로 수집하지 않습니다.",
      "privacy.h9": "9. 방침 변경",
      "privacy.p9": "본 방침은 예고 없이 변경될 수 있습니다. 변경 사항이 있을 경우 본 페이지에서 업데이트됩니다.",
      "privacy.h10": "10. 문의",
      "privacy.p10": "개인정보 관련 문의는 아래로 연락해 주시기 바랍니다.",
      "privacy.nav.home": "홈",
      "privacy.nav.terms": "이용약관",
      "terms.meta.title": "이용약관 — Relora",
      "terms.title": "이용약관",
      "terms.date": "최종 업데이트: 2026년 4월 5일",
      "terms.intro": "본 이용약관(이하 '본 약관')은 Relora(이하 '본 앱')의 이용 조건을 정하는 것입니다. 본 앱을 이용하시기 전에 본 약관을 주의 깊게 읽어 주십시오.",
      "terms.h1": "1. 서비스 내용",
      "terms.p1a": "본 앱은 채팅 스크린샷을 AI로 분석하여 대화의 심리 분석 및 답장 후보 제안 등을 제공하는 참고 정보 제공 서비스입니다.",
      "terms.p1b": "본 앱이 제공하는 정보는 AI에 의한 일반적인 경향에 기반한 참고 정보이며, 전문적인 상담이나 조언이 아닙니다.",
      "terms.h2": "2. 면책 사항",
      "terms.p2.li1": "본 앱의 분석 결과의 정확성, 완전성, 유용성을 보증하지 않습니다",
      "terms.p2.li2": "본 앱의 이용에 기반한 어떠한 행동의 결과에 대해서도 개발자는 책임을 지지 않습니다",
      "terms.p2.li3": "메시지 전송이나 행동에 관한 최종 판단은 사용자 본인의 책임하에 이루어져야 합니다",
      "terms.p2.li4": "본 앱은 연애나 인간관계에 관한 전문적인 상담의 대체물이 아닙니다",
      "terms.h3": "3. 이용 조건",
      "terms.p3.li1": "본 앱은 17세 이상을 대상으로 합니다",
      "terms.p3.li2": "본 앱을 불법적인 목적으로 사용해서는 안 됩니다",
      "terms.p3.li3": "스토킹, 괴롭힘, 기타 타인을 해치는 목적으로의 사용을 금지합니다",
      "terms.h4": "4. 결제에 관하여",
      "terms.p4.li1": "본 앱은 앱 내 결제(구독)를 제공하고 있습니다",
      "terms.p4.li2": "결제는 Apple Inc.를 통해 처리됩니다",
      "terms.p4.li3": "구독은 자동으로 갱신됩니다. 갱신일 24시간 전까지 취소하지 않으면 자동으로 갱신됩니다",
      "terms.p4.li4": "구독의 관리 및 취소는 iOS 설정 앱에서 할 수 있습니다",
      "terms.h5": "5. 지식재산권",
      "terms.p5": "본 앱의 디자인, 코드, 콘텐츠에 관한 지식재산권은 개발자에게 귀속됩니다.",
      "terms.h6": "6. 서비스의 변경·종료",
      "terms.p6": "개발자는 사전 통지 없이 본 앱의 기능을 변경하거나 본 서비스를 종료할 권리를 보유합니다.",
      "terms.h7": "7. 약관의 변경",
      "terms.p7": "본 약관은 예고 없이 변경될 수 있습니다. 변경된 약관은 본 페이지에 게재됨으로써 효력이 발생합니다.",
      "terms.h8": "8. 준거법·관할 법원",
      "terms.p8": "본 약관은 일본법에 준거합니다. 본 약관에 관한 분쟁에 대해서는 도쿄지방법원을 제1심의 전속적 합의 관할 법원으로 합니다.",
      "terms.h9": "9. 문의",
      "terms.p9": "본 약관에 관한 문의는 아래로 연락해 주십시오.",
      "terms.nav.home": "홈",
      "terms.nav.privacy": "개인정보 처리방침"
    },
    de: {
      "meta.title": "Relora — KI-Analyse für Liebes-Nachrichten",
      "meta.description": "Relora analysiert deine Chat-Screenshots mit KI und zeigt dir die Psychologie deines Gegenübers, das Interesse-Level und die besten Antworten. Alles läuft direkt auf deinem Gerät — vollständig privat.",
      "nav.features": "Funktionen",
      "nav.how": "So funktionierts",
      "nav.privacy": "Datenschutz",
      "nav.pricing": "Preise",
      "nav.cta": "Im App Store laden",
      "hero.badge": "100 % On-Device-KI",
      "hero.title_html": 'Deine Liebes-Nachrichten,<br><span>von KI entschlüsselt</span>',
      "hero.desc": "Einfach einen Screenshot hochladen. Relora liest die Psychologie, misst das Interesse und schlägt die perfekte Antwort vor — alles auf deinem Gerät.",
      "hero.cta_primary": "Im App Store laden",
      "hero.cta_secondary": "So funktionierts",
      "features.label": "Features",
      "features.title": "Klarheit für dein Liebesleben",
      "features.desc": "Mehr als nur Antwort-Vorschläge. Relora analysiert die Psychologie, Risiken und Strategie hinter jedem Gespräch.",
      "features.psychology.title": "Psychologie-Analyse",
      "features.psychology.desc": "Verstehe nicht nur den Text, sondern die wahre Absicht und Emotion hinter jeder Nachricht.",
      "features.temperature.title": "Interesse-Score",
      "features.temperature.desc": "Das Interesse deines Gegenübers als Score von 1 bis 10 — Entscheidungen auf Datenbasis statt Bauchgefühl.",
      "features.reply.title": "3 Antwort-Optionen",
      "features.reply.desc": "Erhalte drei passende Antworten — offensiv, sicher und abwartend — jeweils mit Begründung.",
      "features.risk.title": "Risiko-Warnungen",
      "features.risk.desc": "Vermeide Fehler, bevor sie passieren. Relora warnt vor Aktionen, die deiner Beziehung schaden könnten.",
      "features.screenshot.title": "Jede App, jeder Screenshot",
      "features.screenshot.desc": "WhatsApp, Instagram, Tinder, Snapchat — Screenshots aus jeder Messenger-App werden analysiert.",
      "features.private.title": "Vollständig privat",
      "features.private.desc": "Alle KI-Verarbeitung findet auf deinem Gerät statt. Deine Chats werden niemals übertragen.",
      "how.label": "How it works",
      "how.title": "In 3 Schritten zur Analyse",
      "how.desc": "Intuitiv bedienbar, Ergebnis in Sekunden.",
      "how.step1.title": "Screenshot machen",
      "how.step1.desc": "Mach einen Screenshot des Chats, den du analysieren möchtest. Mehrere Bilder sind kein Problem.",
      "how.step2.title": "Kontext angeben",
      "how.step2.desc": "Wähle Beziehungsart, Ziel und Situation aus dem Dropdown. Ergänzungen als Text sind möglich.",
      "how.step3.title": "KI analysiert",
      "how.step3.desc": "Strukturierte Auswertung: Psychologie, Interesse-Level, Antwort-Optionen und Risiken — alles lokal auf deinem Gerät.",
      "privacy_section.title": "Deine Daten gehören dir",
      "privacy_section.desc": "Relora verwendet keinerlei Server. Jede KI-Berechnung läuft vollständig auf deinem iPhone — lokal und sicher.",
      "privacy_section.ondevice.title": "On-Device-KI",
      "privacy_section.ondevice.desc": "Alle KI-Verarbeitung läuft auf deinem iPhone",
      "privacy_section.nodata.title": "Keine Datenübertragung",
      "privacy_section.nodata.desc": "Screenshots und Chats werden nie an externe Server gesendet",
      "privacy_section.delete.title": "Alles löschbar",
      "privacy_section.delete.desc": "App deinstallieren — alle Daten sind sofort weg",
      "pricing.label": "Pricing",
      "pricing.title": "Einfache, faire Preise",
      "pricing.desc": "Kostenlos starten, jederzeit upgraden.",
      "pricing.free.name": "Kostenlos",
      "pricing.free.price": "¥0",
      "pricing.free.f1": "3 Analysen pro Tag",
      "pricing.free.f2": "Basis-Psychologieanalyse",
      "pricing.free.f3": "Antwort-Vorschläge",
      "pricing.free.f4": "Voller Datenschutz",
      "pricing.free.cta": "Kostenlos starten",
      "pricing.premium.badge": "Empfohlen",
      "pricing.premium.name": "Premium",
      "pricing.premium.price_html": '¥980<span>/Monat</span>',
      "pricing.premium.f1": "Unbegrenzte Analysen",
      "pricing.premium.f2": "Tiefe Psychologie- & Strategieanalyse",
      "pricing.premium.f3": "Personengedächtnis & Personalisierung",
      "pricing.premium.f4": "Verlauf & Trendanalyse",
      "pricing.premium.f5": "Voller Datenschutz",
      "pricing.premium.cta": "Premium starten",
      "cta.title": "Liebeskummer? Lass KI mitdenken.",
      "cta.desc": "Relora unterstützt dich bei deinen Entscheidungen.",
      "cta.button": "Im App Store laden",
      "footer.privacy": "Datenschutzerklärung",
      "footer.terms": "Nutzungsbedingungen",
      "footer.contact": "Kontakt",
      "privacy.meta.title": "Datenschutzrichtlinie — Relora",
      "privacy.title": "Datenschutzrichtlinie",
      "privacy.date": "Zuletzt aktualisiert: 5. April 2026",
      "privacy.intro": "Relora (nachfolgend \u201edie App\u201c) wurde mit dem Schutz Ihrer Privatsphäre als höchster Priorität entwickelt. Diese Richtlinie beschreibt den Umgang mit Informationen innerhalb der App.",
      "privacy.h1": "1. Grundsätze",
      "privacy.p1": "Die App funktioniert vollständig auf dem Gerät. Ihre Daten werden niemals an externe Server übertragen. Alle KI-Verarbeitungen finden ausschließlich auf Ihrem Gerät statt.",
      "privacy.h2": "2. Verarbeitete Informationen",
      "privacy.p2": "Folgende Informationen können von der App auf Ihrem Gerät verarbeitet werden. Alle Informationen werden ausschließlich auf Ihrem Gerät gespeichert.",
      "privacy.p2.li1": "Von Ihnen bereitgestellte Screenshot-Bilder",
      "privacy.p2.li2": "Von Ihnen eingegebene Textinformationen (ergänzende Notizen etc.)",
      "privacy.p2.li3": "KI-Analyseergebnisse",
      "privacy.p2.li4": "In-App-Kaufinformationen (über Apple verarbeitet)",
      "privacy.h3": "3. Zweck der Nutzung",
      "privacy.p3": "Die oben genannten Informationen werden ausschließlich für die KI-Analyseverarbeitung auf dem Gerät verwendet.",
      "privacy.h4": "4. Weitergabe an Dritte",
      "privacy.p4": "Die App gibt Ihre Informationen nicht an Dritte weiter. Es werden keinerlei Daten an externe Server übertragen.",
      "privacy.h5": "5. Datenspeicherung",
      "privacy.p5": "Alle Daten werden ausschließlich auf Ihrem Gerät gespeichert. Es wird kein Cloud-Backup durchgeführt.",
      "privacy.h6": "6. Datenlöschung",
      "privacy.p6": "Durch das Löschen der App werden alle damit verbundenen Daten entfernt. Sie können einzelne Daten auch über die App-Einstellungen löschen.",
      "privacy.h7": "7. App Store Datenschutz",
      "privacy.p7.li1": "Data Not Collected: Diese App erfasst keine Benutzerdaten",
      "privacy.p7.li2": "Data Not Linked to You: Daten werden nicht mit Ihrer Identität verknüpft",
      "privacy.h8": "8. Datenschutz für Kinder",
      "privacy.p8": "Die App richtet sich an Nutzer ab 17 Jahren. Wir erfassen wissentlich keine Informationen von Kindern unter 17 Jahren.",
      "privacy.h9": "9. Änderungen der Richtlinie",
      "privacy.p9": "Diese Richtlinie kann ohne vorherige Ankündigung geändert werden. Änderungen werden auf dieser Seite veröffentlicht.",
      "privacy.h10": "10. Kontakt",
      "privacy.p10": "Bei datenschutzbezogenen Anfragen kontaktieren Sie uns bitte unter der folgenden Adresse.",
      "privacy.nav.home": "Startseite",
      "privacy.nav.terms": "Nutzungsbedingungen",
      "terms.meta.title": "Nutzungsbedingungen — Relora",
      "terms.title": "Nutzungsbedingungen",
      "terms.date": "Zuletzt aktualisiert: 5. April 2026",
      "terms.intro": "Diese Nutzungsbedingungen (im Folgenden \u201eBedingungen\u201c) regeln die Nutzung von Relora (im Folgenden \u201eApp\u201c). Bitte lesen Sie diese Bedingungen sorgfältig durch, bevor Sie die App verwenden.",
      "terms.h1": "1. Leistungsbeschreibung",
      "terms.p1a": "Die App ist ein Referenz-Informationsdienst, der KI nutzt, um Chat-Screenshots zu analysieren und psychologische Analysen von Gesprächen sowie Antwortvorschläge bereitzustellen.",
      "terms.p1b": "Die von der App bereitgestellten Informationen sind allgemeine Referenzinformationen, die auf von der KI erkannten Trends basieren, und stellen keine professionelle Beratung dar.",
      "terms.h2": "2. Haftungsausschluss",
      "terms.p2.li1": "Wir übernehmen keine Gewähr für die Richtigkeit, Vollständigkeit oder Nützlichkeit der Analyseergebnisse der App",
      "terms.p2.li2": "Der Entwickler übernimmt keine Verantwortung für die Folgen von Handlungen, die auf der Grundlage der Nutzung der App vorgenommen werden",
      "terms.p2.li3": "Alle endgültigen Entscheidungen bezüglich gesendeter Nachrichten oder ergriffener Maßnahmen liegen in der alleinigen Verantwortung des Nutzers",
      "terms.p2.li4": "Die App ist kein Ersatz für professionelle Beratung in Bezug auf romantische Beziehungen oder zwischenmenschliche Angelegenheiten",
      "terms.h3": "3. Nutzungsvoraussetzungen",
      "terms.p3.li1": "Die App richtet sich an Nutzer ab 17 Jahren",
      "terms.p3.li2": "Die App darf nicht für rechtswidrige Zwecke verwendet werden",
      "terms.p3.li3": "Die Nutzung zum Zweck des Stalkings, der Belästigung oder zur sonstigen Schädigung anderer Personen ist strengstens untersagt",
      "terms.h4": "4. Abrechnung",
      "terms.p4.li1": "Die App bietet In-App-Käufe (Abonnements) an",
      "terms.p4.li2": "Zahlungen werden über Apple Inc. abgewickelt",
      "terms.p4.li3": "Abonnements verlängern sich automatisch. Sofern das Abonnement nicht mindestens 24 Stunden vor dem Verlängerungsdatum gekündigt wird, verlängert es sich automatisch",
      "terms.p4.li4": "Abonnements können über die iOS-Einstellungen-App verwaltet und gekündigt werden",
      "terms.h5": "5. Geistiges Eigentum",
      "terms.p5": "Alle Rechte des geistigen Eigentums am Design, Code und Inhalt der App liegen beim Entwickler.",
      "terms.h6": "6. Änderung und Einstellung des Dienstes",
      "terms.p6": "Der Entwickler behält sich das Recht vor, die Funktionen der App zu ändern oder den Dienst jederzeit ohne vorherige Ankündigung einzustellen.",
      "terms.h7": "7. Änderungen dieser Bedingungen",
      "terms.p7": "Diese Bedingungen können ohne Vorankündigung aktualisiert werden. Geänderte Bedingungen treten mit ihrer Veröffentlichung auf dieser Seite in Kraft.",
      "terms.h8": "8. Anwendbares Recht und Gerichtsstand",
      "terms.p8": "Diese Bedingungen unterliegen dem japanischen Recht. Für Streitigkeiten im Zusammenhang mit diesen Bedingungen ist das Bezirksgericht Tokio als ausschließlicher Gerichtsstand erster Instanz vereinbart.",
      "terms.h9": "9. Kontakt",
      "terms.p9": "Für Anfragen zu diesen Bedingungen wenden Sie sich bitte an folgende Adresse.",
      "terms.nav.home": "Startseite",
      "terms.nav.privacy": "Datenschutzerklärung"
    },
    fr: {
      "meta.title": "Relora — IA d'analyse des messages amoureux",
      "meta.description": "Relora analyse vos captures d'écran de chat grâce à l'IA pour décrypter la psychologie, le niveau d'intérêt et les meilleures réponses. Tout se passe sur votre appareil, sans compromis sur votre vie privée.",
      "nav.features": "Fonctionnalités",
      "nav.how": "Comment ça marche",
      "nav.privacy": "Confidentialité",
      "nav.pricing": "Tarifs",
      "nav.cta": "Disponible sur l'App Store",
      "hero.badge": "100 % IA locale",
      "hero.title_html": 'Vos messages amoureux<br><span>décryptés par l\'IA</span>',
      "hero.desc": "Importez une capture d'écran de conversation. Relora analyse la psychologie, jauge l'intérêt et vous suggère la meilleure réponse — entièrement sur votre appareil.",
      "hero.cta_primary": "Télécharger sur l'App Store",
      "hero.cta_secondary": "Voir comment ça marche",
      "features.label": "Features",
      "features.title": "Voyez clair dans votre vie amoureuse",
      "features.desc": "Bien plus que des suggestions de réponse. Relora analyse la psychologie, les risques et la stratégie derrière chaque échange.",
      "features.psychology.title": "Analyse psychologique",
      "features.psychology.desc": "Allez au-delà des mots. Comprenez les vraies intentions et émotions derrière chaque message.",
      "features.temperature.title": "Score d'intérêt",
      "features.temperature.desc": "Visualisez le niveau d'intérêt de l'autre de 1 à 10. Décidez avec des données, pas des suppositions.",
      "features.reply.title": "3 options de réponse",
      "features.reply.desc": "Trois réponses sur mesure — audacieuse, prudente ou attentiste — avec une explication pour chacune.",
      "features.risk.title": "Alertes de risque",
      "features.risk.desc": "Anticipez les faux pas. Relora vous signale les comportements qui pourraient nuire à votre relation.",
      "features.screenshot.title": "Toutes les apps supportées",
      "features.screenshot.desc": "WhatsApp, Instagram, Tinder, Snapchat — analysez les captures de n'importe quelle messagerie.",
      "features.private.title": "Totalement privé",
      "features.private.desc": "Tout le traitement IA s'effectue sur votre appareil. Vos conversations ne quittent jamais votre téléphone.",
      "how.label": "How it works",
      "how.title": "Une analyse en 3 étapes",
      "how.desc": "Intuitif et rapide — des insights profonds en quelques secondes.",
      "how.step1.title": "Prenez une capture",
      "how.step1.desc": "Capturez la conversation qui vous intéresse. Plusieurs captures sont acceptées.",
      "how.step2.title": "Définissez le contexte",
      "how.step2.desc": "Sélectionnez la nature de la relation, votre objectif et la situation dans le menu. Ajoutez des précisions si besoin.",
      "how.step3.title": "L'IA analyse",
      "how.step3.desc": "Résultats structurés : psychologie, score d'intérêt, options de réponse et risques — tout traité localement.",
      "privacy_section.title": "Vos données vous appartiennent",
      "privacy_section.desc": "Relora ne fait appel à aucun serveur. Chaque traitement IA s'exécute entièrement sur votre iPhone.",
      "privacy_section.ondevice.title": "IA sur l'appareil",
      "privacy_section.ondevice.desc": "Tout le traitement IA s'exécute sur votre iPhone",
      "privacy_section.nodata.title": "Aucune transmission de données",
      "privacy_section.nodata.desc": "Captures et conversations ne sont jamais envoyées à des serveurs externes",
      "privacy_section.delete.title": "Suppression totale",
      "privacy_section.delete.desc": "Désinstallez l'app et toutes vos données disparaissent",
      "pricing.label": "Pricing",
      "pricing.title": "Des tarifs simples et clairs",
      "pricing.desc": "Commencez gratuitement, passez premium quand vous voulez.",
      "pricing.free.name": "Gratuit",
      "pricing.free.price": "¥0",
      "pricing.free.f1": "3 analyses par jour",
      "pricing.free.f2": "Analyse psychologique de base",
      "pricing.free.f3": "Suggestions de réponses",
      "pricing.free.f4": "Protection totale de la vie privée",
      "pricing.free.cta": "Commencer gratuitement",
      "pricing.premium.badge": "Recommandé",
      "pricing.premium.name": "Premium",
      "pricing.premium.price_html": '¥980<span>/mois</span>',
      "pricing.premium.f1": "Analyses illimitées",
      "pricing.premium.f2": "Analyse psychologique approfondie & stratégique",
      "pricing.premium.f3": "Mémoire par personne & personnalisation",
      "pricing.premium.f4": "Historique & analyse des tendances",
      "pricing.premium.f5": "Protection totale de la vie privée",
      "pricing.premium.cta": "Passer à Premium",
      "cta.title": "Laissez l'IA vous aider en amour",
      "cta.desc": "Relora vous accompagne dans vos décisions.",
      "cta.button": "Télécharger sur l'App Store",
      "footer.privacy": "Politique de confidentialité",
      "footer.terms": "Conditions d'utilisation",
      "footer.contact": "Contact",
      "privacy.meta.title": "Politique de confidentialité — Relora",
      "privacy.title": "Politique de confidentialité",
      "privacy.date": "Dernière mise à jour : 5 avril 2026",
      "privacy.intro": "Relora (ci-après « l'Application ») a été conçue en plaçant la protection de votre vie privée au premier plan. Cette politique décrit la manière dont les informations sont traitées au sein de l'Application.",
      "privacy.h1": "1. Principes fondamentaux",
      "privacy.p1": "L'Application fonctionne entièrement sur l'appareil. Vos données ne sont jamais transmises à des serveurs externes. Tous les traitements par IA sont effectués sur votre appareil.",
      "privacy.h2": "2. Informations traitées",
      "privacy.p2": "Les informations suivantes peuvent être traitées par l'Application sur votre appareil. Toutes ces informations sont stockées exclusivement sur votre appareil.",
      "privacy.p2.li1": "Images de captures d'écran que vous fournissez",
      "privacy.p2.li2": "Informations textuelles que vous saisissez (notes complémentaires, etc.)",
      "privacy.p2.li3": "Résultats d'analyse par IA",
      "privacy.p2.li4": "Informations relatives aux achats intégrés (traités via Apple)",
      "privacy.h3": "3. Finalité de l'utilisation",
      "privacy.p3": "Les informations susmentionnées sont utilisées exclusivement pour le traitement d'analyse par IA sur l'appareil.",
      "privacy.h4": "4. Communication à des tiers",
      "privacy.p4": "L'Application ne communique pas vos informations à des tiers. Aucune donnée n'est transmise à des serveurs externes.",
      "privacy.h5": "5. Conservation des données",
      "privacy.p5": "Toutes les données sont stockées exclusivement sur votre appareil. Aucune sauvegarde dans le cloud n'est effectuée.",
      "privacy.h6": "6. Suppression des données",
      "privacy.p6": "La suppression de l'Application entraîne la suppression de toutes les données associées. Vous pouvez également supprimer des données individuelles depuis les paramètres de l'Application.",
      "privacy.h7": "7. Confidentialité sur l'App Store",
      "privacy.p7.li1": "Data Not Collected : cette application ne collecte aucune donnée utilisateur",
      "privacy.p7.li2": "Data Not Linked to You : aucune donnée n'est associée à votre identité",
      "privacy.h8": "8. Confidentialité des mineurs",
      "privacy.p8": "L'Application est destinée aux utilisateurs âgés de 17 ans et plus. Nous ne collectons pas sciemment d'informations auprès d'enfants de moins de 17 ans.",
      "privacy.h9": "9. Modifications de la politique",
      "privacy.p9": "Cette politique peut être modifiée sans préavis. Toute modification sera reflétée sur cette page.",
      "privacy.h10": "10. Contact",
      "privacy.p10": "Pour toute question relative à la confidentialité, veuillez nous contacter à l'adresse ci-dessous.",
      "privacy.nav.home": "Accueil",
      "privacy.nav.terms": "Conditions d'utilisation",
      "terms.meta.title": "Conditions d'utilisation — Relora",
      "terms.title": "Conditions d'utilisation",
      "terms.date": "Dernière mise à jour : 5 avril 2026",
      "terms.intro": "Les présentes conditions d'utilisation (ci-après « les Conditions ») régissent l'utilisation de Relora (ci-après « l'Application »). Veuillez lire attentivement ces Conditions avant d'utiliser l'Application.",
      "terms.h1": "1. Description du service",
      "terms.p1a": "L'Application est un service d'information de référence qui utilise l'IA pour analyser des captures d'écran de conversations et fournit des analyses psychologiques des échanges ainsi que des suggestions de réponses.",
      "terms.p1b": "Les informations fournies par l'Application sont des informations de référence générales basées sur les tendances identifiées par l'IA et ne constituent pas un conseil ou un accompagnement professionnel.",
      "terms.h2": "2. Limitation de responsabilité",
      "terms.p2.li1": "Nous ne garantissons pas l'exactitude, l'exhaustivité ou l'utilité des résultats d'analyse de l'Application",
      "terms.p2.li2": "Le développeur décline toute responsabilité quant aux conséquences des actions entreprises sur la base de l'utilisation de l'Application",
      "terms.p2.li3": "Toutes les décisions finales concernant les messages envoyés ou les actions entreprises relèvent de la seule responsabilité de l'utilisateur",
      "terms.p2.li4": "L'Application ne se substitue pas à un accompagnement professionnel en matière de relations amoureuses ou interpersonnelles",
      "terms.h3": "3. Conditions d'utilisation",
      "terms.p3.li1": "L'Application est destinée aux utilisateurs âgés de 17 ans et plus",
      "terms.p3.li2": "L'Application ne doit pas être utilisée à des fins illégales",
      "terms.p3.li3": "L'utilisation à des fins de harcèlement, de stalking ou de toute autre atteinte à autrui est strictement interdite",
      "terms.h4": "4. Facturation",
      "terms.p4.li1": "L'Application propose des achats intégrés (abonnements)",
      "terms.p4.li2": "Les paiements sont traités par Apple Inc.",
      "terms.p4.li3": "Les abonnements se renouvellent automatiquement. Sauf annulation au moins 24 heures avant la date de renouvellement, l'abonnement sera automatiquement renouvelé",
      "terms.p4.li4": "Les abonnements peuvent être gérés et annulés via l'application Réglages d'iOS",
      "terms.h5": "5. Propriété intellectuelle",
      "terms.p5": "Tous les droits de propriété intellectuelle relatifs au design, au code et au contenu de l'Application appartiennent au développeur.",
      "terms.h6": "6. Modification et résiliation du service",
      "terms.p6": "Le développeur se réserve le droit de modifier les fonctionnalités de l'Application ou de mettre fin au service à tout moment sans préavis.",
      "terms.h7": "7. Modification des présentes Conditions",
      "terms.p7": "Les présentes Conditions peuvent être mises à jour sans préavis. Les Conditions modifiées prennent effet dès leur publication sur cette page.",
      "terms.h8": "8. Droit applicable et juridiction compétente",
      "terms.p8": "Les présentes Conditions sont régies par le droit japonais. Tout litige relatif aux présentes Conditions sera soumis à la compétence exclusive du Tribunal de district de Tokyo en première instance.",
      "terms.h9": "9. Contact",
      "terms.p9": "Pour toute question relative aux présentes Conditions, veuillez nous contacter à l'adresse ci-dessous.",
      "terms.nav.home": "Accueil",
      "terms.nav.privacy": "Politique de confidentialité"
    },
    it: {
      "meta.title": "Relora — IA per l'analisi dei messaggi d'amore",
      "meta.description": "Relora analizza gli screenshot delle tue chat con l'IA per svelare la psicologia dell'altro, il livello d'interesse e le migliori risposte. Tutto avviene sul tuo dispositivo, con la tua privacy sempre al sicuro.",
      "nav.features": "Funzionalità",
      "nav.how": "Come funziona",
      "nav.privacy": "Privacy",
      "nav.pricing": "Prezzi",
      "nav.cta": "Scarica sull'App Store",
      "hero.badge": "100% IA on-device",
      "hero.title_html": 'I tuoi messaggi d\'amore<br><span>decifrati dall\'IA</span>',
      "hero.desc": "Carica uno screenshot della chat. Relora legge la psicologia, misura l'interesse e ti suggerisce la risposta perfetta — tutto sul tuo dispositivo.",
      "hero.cta_primary": "Scarica sull'App Store",
      "hero.cta_secondary": "Scopri come funziona",
      "features.label": "Features",
      "features.title": "Chiarezza nella tua vita amorosa",
      "features.desc": "Non solo suggerimenti di risposta. Relora analizza la psicologia, i rischi e la strategia dietro ogni conversazione.",
      "features.psychology.title": "Analisi psicologica",
      "features.psychology.desc": "Vai oltre le parole. Comprendi le vere intenzioni ed emozioni dietro ogni messaggio.",
      "features.temperature.title": "Punteggio d'interesse",
      "features.temperature.desc": "Il livello d'interesse dell'altro visualizzato da 1 a 10. Decidi con i dati, non con l'istinto.",
      "features.reply.title": "3 opzioni di risposta",
      "features.reply.desc": "Tre risposte su misura — audace, prudente e attendista — ognuna con la sua spiegazione.",
      "features.risk.title": "Avvisi di rischio",
      "features.risk.desc": "Previeni gli errori prima di commetterli. Relora segnala le azioni che potrebbero danneggiare il tuo rapporto.",
      "features.screenshot.title": "Qualsiasi app, qualsiasi screenshot",
      "features.screenshot.desc": "WhatsApp, Instagram, Tinder, Snapchat — analizza screenshot da qualsiasi app di messaggistica.",
      "features.private.title": "Completamente privato",
      "features.private.desc": "Tutta l'elaborazione IA avviene sul tuo dispositivo. Le tue conversazioni non vengono mai trasmesse.",
      "how.label": "How it works",
      "how.title": "Analisi in 3 passi",
      "how.desc": "Semplice e intuitivo, risultati profondi in pochi secondi.",
      "how.step1.title": "Scatta uno screenshot",
      "how.step1.desc": "Cattura la chat che vuoi analizzare. Vanno bene anche più screenshot insieme.",
      "how.step2.title": "Imposta il contesto",
      "how.step2.desc": "Scegli tipo di relazione, obiettivo e situazione dal menu a tendina. Aggiungi note se necessario.",
      "how.step3.title": "L'IA analizza",
      "how.step3.desc": "Risultati strutturati: psicologia, punteggio d'interesse, opzioni di risposta e rischi — tutto elaborato localmente.",
      "privacy_section.title": "I tuoi dati sono tuoi",
      "privacy_section.desc": "Relora non utilizza alcun server. Ogni elaborazione IA avviene interamente sul tuo iPhone.",
      "privacy_section.ondevice.title": "IA on-device",
      "privacy_section.ondevice.desc": "Tutta l'elaborazione IA gira sul tuo iPhone",
      "privacy_section.nodata.title": "Nessuna trasmissione di dati",
      "privacy_section.nodata.desc": "Screenshot e chat non vengono mai inviati a server esterni",
      "privacy_section.delete.title": "Eliminazione completa",
      "privacy_section.delete.desc": "Disinstalla l'app e tutti i tuoi dati scompaiono",
      "pricing.label": "Pricing",
      "pricing.title": "Prezzi semplici e trasparenti",
      "pricing.desc": "Inizia gratis, passa a Premium quando vuoi.",
      "pricing.free.name": "Gratuito",
      "pricing.free.price": "¥0",
      "pricing.free.f1": "3 analisi al giorno",
      "pricing.free.f2": "Analisi psicologica di base",
      "pricing.free.f3": "Suggerimenti di risposta",
      "pricing.free.f4": "Privacy completamente protetta",
      "pricing.free.cta": "Inizia gratis",
      "pricing.premium.badge": "Consigliato",
      "pricing.premium.name": "Premium",
      "pricing.premium.price_html": '¥980<span>/mese</span>',
      "pricing.premium.f1": "Analisi illimitate",
      "pricing.premium.f2": "Analisi psicologica approfondita e strategica",
      "pricing.premium.f3": "Memoria per persona e personalizzazione",
      "pricing.premium.f4": "Storico e analisi delle tendenze",
      "pricing.premium.f5": "Privacy completamente protetta",
      "pricing.premium.cta": "Passa a Premium",
      "cta.title": "Lascia che l'IA ti aiuti in amore",
      "cta.desc": "Relora supporta le tue decisioni.",
      "cta.button": "Scarica sull'App Store",
      "footer.privacy": "Informativa sulla privacy",
      "footer.terms": "Termini di servizio",
      "footer.contact": "Contattaci",
      "privacy.meta.title": "Informativa sulla privacy — Relora",
      "privacy.title": "Informativa sulla privacy",
      "privacy.date": "Ultimo aggiornamento: 5 aprile 2026",
      "privacy.intro": "Relora (di seguito «l'App») è progettata ponendo la tutela della privacy degli utenti come priorità assoluta. La presente informativa descrive le modalità di gestione delle informazioni nell'ambito dell'App.",
      "privacy.h1": "1. Principi fondamentali",
      "privacy.p1": "L'App funziona interamente sul dispositivo. I dati degli utenti non vengono mai trasmessi a server esterni. Tutta l'elaborazione AI viene eseguita sul dispositivo dell'utente.",
      "privacy.h2": "2. Informazioni trattate",
      "privacy.p2": "Le seguenti informazioni possono essere elaborate dall'App sul dispositivo. Tutte vengono memorizzate esclusivamente sul dispositivo dell'utente.",
      "privacy.p2.li1": "Immagini di screenshot fornite dall'utente",
      "privacy.p2.li2": "Informazioni testuali inserite dall'utente (note supplementari, ecc.)",
      "privacy.p2.li3": "Risultati dell'analisi AI",
      "privacy.p2.li4": "Informazioni sugli acquisti in-app (elaborati tramite Apple)",
      "privacy.h3": "3. Finalità del trattamento",
      "privacy.p3": "Le informazioni di cui sopra vengono utilizzate esclusivamente per l'elaborazione dell'analisi AI sul dispositivo.",
      "privacy.h4": "4. Comunicazione a terzi",
      "privacy.p4": "L'App non comunica le informazioni degli utenti a terzi. Nessun dato viene trasmesso a server esterni.",
      "privacy.h5": "5. Conservazione dei dati",
      "privacy.p5": "Tutti i dati vengono memorizzati esclusivamente sul dispositivo dell'utente. Non viene eseguito alcun backup su cloud.",
      "privacy.h6": "6. Cancellazione dei dati",
      "privacy.p6": "L'eliminazione dell'App comporta la cancellazione di tutti i dati ad essa associati. È inoltre possibile eliminare singoli dati dalle impostazioni dell'App.",
      "privacy.h7": "7. Privacy sull'App Store",
      "privacy.p7.li1": "Data Not Collected: questa app non raccoglie dati degli utenti",
      "privacy.p7.li2": "Data Not Linked to You: i dati non sono collegati alla tua identità",
      "privacy.h8": "8. Privacy dei minori",
      "privacy.p8": "L'App è destinata a utenti di 17 anni e oltre. Non raccogliamo consapevolmente informazioni da minori di 17 anni.",
      "privacy.h9": "9. Modifiche all'informativa",
      "privacy.p9": "La presente informativa può essere modificata senza preavviso. Eventuali modifiche saranno riportate su questa pagina.",
      "privacy.h10": "10. Contatti",
      "privacy.p10": "Per qualsiasi domanda relativa alla privacy, si prega di contattarci all'indirizzo indicato di seguito.",
      "privacy.nav.home": "Home",
      "privacy.nav.terms": "Termini di utilizzo",
      "terms.meta.title": "Termini di servizio — Relora",
      "terms.title": "Termini di servizio",
      "terms.date": "Ultimo aggiornamento: 5 aprile 2026",
      "terms.intro": "I presenti Termini di servizio (di seguito «Termini») disciplinano l'utilizzo di Relora (di seguito «l'App»). Si prega di leggere attentamente i presenti Termini prima di utilizzare l'App.",
      "terms.h1": "1. Descrizione del servizio",
      "terms.p1a": "L'App è un servizio di informazioni di riferimento che utilizza l'intelligenza artificiale per analizzare screenshot di conversazioni e fornisce analisi psicologiche delle conversazioni e suggerimenti di risposta.",
      "terms.p1b": "Le informazioni fornite dall'App sono informazioni di riferimento generali basate sulle tendenze identificate dall'IA e non costituiscono consulenza o assistenza professionale.",
      "terms.h2": "2. Limitazione di responsabilità",
      "terms.p2.li1": "Non forniamo alcuna garanzia in merito all'accuratezza, alla completezza o all'utilità dei risultati di analisi dell'App",
      "terms.p2.li2": "Lo sviluppatore non si assume alcuna responsabilità per le conseguenze di azioni intraprese sulla base dell'utilizzo dell'App",
      "terms.p2.li3": "Tutte le decisioni finali riguardanti i messaggi inviati o le azioni intraprese sono di esclusiva responsabilità dell'utente",
      "terms.p2.li4": "L'App non sostituisce la consulenza professionale in materia di relazioni sentimentali o interpersonali",
      "terms.h3": "3. Condizioni di utilizzo",
      "terms.p3.li1": "L'App è destinata agli utenti di età pari o superiore a 17 anni",
      "terms.p3.li2": "L'App non deve essere utilizzata per scopi illegali",
      "terms.p3.li3": "È severamente vietato utilizzare l'App per stalking, molestie o qualsiasi altro fine lesivo nei confronti di terzi",
      "terms.h4": "4. Acquisti e abbonamenti",
      "terms.p4.li1": "L'App offre acquisti in-app (abbonamenti)",
      "terms.p4.li2": "I pagamenti vengono elaborati tramite Apple Inc.",
      "terms.p4.li3": "Gli abbonamenti si rinnovano automaticamente. Salvo disdetta almeno 24 ore prima della data di rinnovo, l'abbonamento si rinnoverà automaticamente",
      "terms.p4.li4": "Gli abbonamenti possono essere gestiti e cancellati tramite l'app Impostazioni di iOS",
      "terms.h5": "5. Proprietà intellettuale",
      "terms.p5": "Tutti i diritti di proprietà intellettuale relativi al design, al codice e ai contenuti dell'App appartengono allo sviluppatore.",
      "terms.h6": "6. Modifica e cessazione del servizio",
      "terms.p6": "Lo sviluppatore si riserva il diritto di modificare le funzionalità dell'App o di interrompere il servizio in qualsiasi momento senza preavviso.",
      "terms.h7": "7. Modifiche ai presenti Termini",
      "terms.p7": "I presenti Termini possono essere aggiornati senza preavviso. I Termini modificati entrano in vigore al momento della loro pubblicazione su questa pagina.",
      "terms.h8": "8. Legge applicabile e foro competente",
      "terms.p8": "I presenti Termini sono disciplinati dalla legge giapponese. Qualsiasi controversia relativa ai presenti Termini sarà devoluta alla competenza esclusiva del Tribunale distrettuale di Tokyo come foro di primo grado.",
      "terms.h9": "9. Contatti",
      "terms.p9": "Per qualsiasi domanda relativa ai presenti Termini, si prega di contattarci all'indirizzo indicato di seguito.",
      "terms.nav.home": "Home",
      "terms.nav.privacy": "Informativa sulla privacy"
    },
    es: {
      "meta.title": "Relora — IA para analizar mensajes de amor",
      "meta.description": "Relora analiza tus capturas de pantalla de chat con IA para revelar la psicología, el nivel de interés y las mejores respuestas. Todo ocurre en tu dispositivo, con tu privacidad completamente protegida.",
      "nav.features": "Funciones",
      "nav.how": "Cómo funciona",
      "nav.privacy": "Privacidad",
      "nav.pricing": "Precios",
      "nav.cta": "Descargar en App Store",
      "hero.badge": "IA 100% local",
      "hero.title_html": 'Tus mensajes de amor,<br><span>descifrados por la IA</span>',
      "hero.desc": "Sube una captura de tu chat. Relora lee la psicología, mide el interés y te sugiere la respuesta perfecta — todo en tu dispositivo.",
      "hero.cta_primary": "Descargar en App Store",
      "hero.cta_secondary": "Ver cómo funciona",
      "features.label": "Features",
      "features.title": "Claridad para tu vida amorosa",
      "features.desc": "Mucho más que sugerencias de respuesta. Relora analiza la psicología, los riesgos y la estrategia detrás de cada conversación.",
      "features.psychology.title": "Análisis psicológico",
      "features.psychology.desc": "Ve más allá de las palabras. Entiende las verdaderas intenciones y emociones detrás de cada mensaje.",
      "features.temperature.title": "Puntuación de interés",
      "features.temperature.desc": "El nivel de interés de la otra persona del 1 al 10. Toma decisiones con datos, no con corazonadas.",
      "features.reply.title": "3 opciones de respuesta",
      "features.reply.desc": "Tres respuestas a medida — atrevida, prudente y expectante — cada una con su explicación.",
      "features.risk.title": "Alertas de riesgo",
      "features.risk.desc": "Evita errores antes de cometerlos. Relora te avisa de las acciones que podrían perjudicar tu relación.",
      "features.screenshot.title": "Cualquier app, cualquier captura",
      "features.screenshot.desc": "WhatsApp, Instagram, Tinder, Snapchat — analiza capturas de cualquier app de mensajería.",
      "features.private.title": "Totalmente privado",
      "features.private.desc": "Todo el procesamiento de IA ocurre en tu dispositivo. Tus conversaciones nunca se envían a ningún lado.",
      "how.label": "How it works",
      "how.title": "Análisis completo en 3 pasos",
      "how.desc": "Intuitivo y rápido — insights profundos en cuestión de segundos.",
      "how.step1.title": "Toma una captura",
      "how.step1.desc": "Captura el chat que quieres analizar. Puedes subir varias imágenes a la vez.",
      "how.step2.title": "Define el contexto",
      "how.step2.desc": "Elige tipo de relación, objetivo y situación en el menú. Añade notas si lo necesitas.",
      "how.step3.title": "La IA analiza",
      "how.step3.desc": "Resultados estructurados: psicología, nivel de interés, opciones de respuesta y riesgos — todo procesado localmente.",
      "privacy_section.title": "Tus datos son tuyos",
      "privacy_section.desc": "Relora no usa ningún servidor. Cada proceso de IA se ejecuta íntegramente en tu iPhone.",
      "privacy_section.ondevice.title": "IA en el dispositivo",
      "privacy_section.ondevice.desc": "Todo el procesamiento de IA se ejecuta en tu iPhone",
      "privacy_section.nodata.title": "Sin transmisión de datos",
      "privacy_section.nodata.desc": "Las capturas y conversaciones nunca se envían a servidores externos",
      "privacy_section.delete.title": "Eliminación completa",
      "privacy_section.delete.desc": "Desinstala la app y todos tus datos desaparecen",
      "pricing.label": "Pricing",
      "pricing.title": "Precios simples y claros",
      "pricing.desc": "Empieza gratis, mejora cuando quieras.",
      "pricing.free.name": "Gratis",
      "pricing.free.price": "¥0",
      "pricing.free.f1": "3 análisis por día",
      "pricing.free.f2": "Análisis psicológico básico",
      "pricing.free.f3": "Sugerencias de respuesta",
      "pricing.free.f4": "Privacidad completamente protegida",
      "pricing.free.cta": "Empezar gratis",
      "pricing.premium.badge": "Recomendado",
      "pricing.premium.name": "Premium",
      "pricing.premium.price_html": '¥980<span>/mes</span>',
      "pricing.premium.f1": "Análisis ilimitados",
      "pricing.premium.f2": "Análisis psicológico profundo y estratégico",
      "pricing.premium.f3": "Memoria por persona y personalización",
      "pricing.premium.f4": "Historial y análisis de tendencias",
      "pricing.premium.f5": "Privacidad completamente protegida",
      "pricing.premium.cta": "Ir a Premium",
      "cta.title": "Deja que la IA te ayude en el amor",
      "cta.desc": "Relora apoya tus decisiones.",
      "cta.button": "Descargar en App Store",
      "footer.privacy": "Política de privacidad",
      "footer.terms": "Términos de servicio",
      "footer.contact": "Contacto",
      "privacy.meta.title": "Política de privacidad — Relora",
      "privacy.title": "Política de privacidad",
      "privacy.date": "Última actualización: 5 de abril de 2026",
      "privacy.intro": "Relora (en adelante, «la App») ha sido diseñada con la privacidad del usuario como prioridad absoluta. Esta política describe cómo se gestiona la información dentro de la App.",
      "privacy.h1": "1. Principios fundamentales",
      "privacy.p1": "La App funciona completamente en el dispositivo. Sus datos nunca se transmiten a servidores externos. Todo el procesamiento de IA se realiza en su dispositivo.",
      "privacy.h2": "2. Información procesada",
      "privacy.p2": "La siguiente información puede ser procesada por la App en su dispositivo. Toda ella se almacena exclusivamente en su dispositivo.",
      "privacy.p2.li1": "Imágenes de capturas de pantalla que usted proporcione",
      "privacy.p2.li2": "Información de texto que usted introduzca (notas complementarias, etc.)",
      "privacy.p2.li3": "Resultados del análisis de IA",
      "privacy.p2.li4": "Información sobre compras dentro de la app (procesadas a través de Apple)",
      "privacy.h3": "3. Finalidad del uso",
      "privacy.p3": "La información anterior se utiliza exclusivamente para el procesamiento del análisis de IA en el dispositivo.",
      "privacy.h4": "4. Comunicación a terceros",
      "privacy.p4": "La App no comparte su información con terceros. No se transmite ningún dato a servidores externos.",
      "privacy.h5": "5. Almacenamiento de datos",
      "privacy.p5": "Todos los datos se almacenan exclusivamente en su dispositivo. No se realiza ninguna copia de seguridad en la nube.",
      "privacy.h6": "6. Eliminación de datos",
      "privacy.p6": "Al eliminar la App, se borran todos los datos asociados a ella. También puede eliminar datos individuales desde los ajustes de la App.",
      "privacy.h7": "7. Privacidad en el App Store",
      "privacy.p7.li1": "Data Not Collected: esta app no recopila datos de los usuarios",
      "privacy.p7.li2": "Data Not Linked to You: los datos no están vinculados a su identidad",
      "privacy.h8": "8. Privacidad de los menores",
      "privacy.p8": "La App está destinada a usuarios mayores de 17 años. No recopilamos intencionadamente información de menores de 17 años.",
      "privacy.h9": "9. Cambios en la política",
      "privacy.p9": "Esta política puede modificarse sin previo aviso. Cualquier cambio se reflejará en esta página.",
      "privacy.h10": "10. Contacto",
      "privacy.p10": "Para cualquier consulta relacionada con la privacidad, póngase en contacto con nosotros en la dirección indicada a continuación.",
      "privacy.nav.home": "Inicio",
      "privacy.nav.terms": "Términos de uso",
      "terms.meta.title": "Términos de servicio — Relora",
      "terms.title": "Términos de servicio",
      "terms.date": "Última actualización: 5 de abril de 2026",
      "terms.intro": "Los presentes Términos de servicio (en adelante, «los Términos») rigen el uso de Relora (en adelante, «la App»). Le rogamos que lea atentamente estos Términos antes de utilizar la App.",
      "terms.h1": "1. Descripción del servicio",
      "terms.p1a": "La App es un servicio de información de referencia que utiliza inteligencia artificial para analizar capturas de pantalla de conversaciones y proporciona análisis psicológicos de los intercambios, así como sugerencias de respuesta.",
      "terms.p1b": "La información proporcionada por la App es información de referencia general basada en las tendencias identificadas por la IA y no constituye asesoramiento o acompañamiento profesional.",
      "terms.h2": "2. Limitación de responsabilidad",
      "terms.p2.li1": "No garantizamos la exactitud, la integridad ni la utilidad de los resultados de análisis de la App",
      "terms.p2.li2": "El desarrollador no asume ninguna responsabilidad por las consecuencias de las acciones emprendidas en base al uso de la App",
      "terms.p2.li3": "Todas las decisiones finales relativas a los mensajes enviados o las acciones emprendidas son de exclusiva responsabilidad del usuario",
      "terms.p2.li4": "La App no sustituye el asesoramiento profesional en materia de relaciones amorosas o interpersonales",
      "terms.h3": "3. Condiciones de uso",
      "terms.p3.li1": "La App está destinada a usuarios mayores de 17 años",
      "terms.p3.li2": "La App no debe utilizarse con fines ilegales",
      "terms.p3.li3": "Queda estrictamente prohibido el uso de la App con fines de acoso, hostigamiento o cualquier otro propósito que cause daño a terceros",
      "terms.h4": "4. Facturación",
      "terms.p4.li1": "La App ofrece compras dentro de la aplicación (suscripciones)",
      "terms.p4.li2": "Los pagos se procesan a través de Apple Inc.",
      "terms.p4.li3": "Las suscripciones se renuevan automáticamente. A menos que se cancelen al menos 24 horas antes de la fecha de renovación, la suscripción se renovará de forma automática",
      "terms.p4.li4": "Las suscripciones pueden gestionarse y cancelarse a través de la app de Configuración de iOS",
      "terms.h5": "5. Propiedad intelectual",
      "terms.p5": "Todos los derechos de propiedad intelectual sobre el diseño, el código y el contenido de la App pertenecen al desarrollador.",
      "terms.h6": "6. Modificación y cese del servicio",
      "terms.p6": "El desarrollador se reserva el derecho de modificar las funcionalidades de la App o de poner fin al servicio en cualquier momento sin previo aviso.",
      "terms.h7": "7. Modificaciones de los presentes Términos",
      "terms.p7": "Los presentes Términos podrán actualizarse sin previo aviso. Los Términos modificados entrarán en vigor en el momento de su publicación en esta página.",
      "terms.h8": "8. Ley aplicable y jurisdicción competente",
      "terms.p8": "Los presentes Términos se rigen por la legislación japonesa. Cualquier controversia relativa a los presentes Términos quedará sujeta a la jurisdicción exclusiva del Tribunal de Distrito de Tokio como tribunal de primera instancia.",
      "terms.h9": "9. Contacto",
      "terms.p9": "Para cualquier consulta relativa a los presentes Términos, póngase en contacto con nosotros en la dirección indicada a continuación.",
      "terms.nav.home": "Inicio",
      "terms.nav.privacy": "Política de privacidad"
    },
    pt: {
      "meta.title": "Relora — IA para análise de mensagens amorosas",
      "meta.description": "O Relora usa IA para analisar capturas de ecrã das suas conversas e revelar a psicologia, o nível de interesse e as melhores respostas. Tudo acontece no seu dispositivo, com total proteção da privacidade.",
      "nav.features": "Funcionalidades",
      "nav.how": "Como funciona",
      "nav.privacy": "Privacidade",
      "nav.pricing": "Preços",
      "nav.cta": "Disponível na App Store",
      "hero.badge": "IA 100% local",
      "hero.title_html": 'As suas mensagens amorosas<br><span>descodificadas pela IA</span>',
      "hero.desc": "Basta carregar uma captura de ecrã da conversa. O Relora lê a psicologia, mede o interesse e sugere a resposta perfeita — tudo no seu dispositivo.",
      "hero.cta_primary": "Descarregar na App Store",
      "hero.cta_secondary": "Ver como funciona",
      "features.label": "Features",
      "features.title": "Clareza para a sua vida amorosa",
      "features.desc": "Muito mais do que sugestões de resposta. O Relora analisa a psicologia, os riscos e a estratégia por trás de cada conversa.",
      "features.psychology.title": "Análise psicológica",
      "features.psychology.desc": "Vá além das palavras. Compreenda as verdadeiras intenções e emoções por trás de cada mensagem.",
      "features.temperature.title": "Pontuação de interesse",
      "features.temperature.desc": "O nível de interesse da outra pessoa de 1 a 10. Tome decisões com base em dados, não em intuições.",
      "features.reply.title": "3 opções de resposta",
      "features.reply.desc": "Três respostas à medida — ousada, prudente e expectante — cada uma com a sua explicação.",
      "features.risk.title": "Alertas de risco",
      "features.risk.desc": "Evite erros antes de os cometer. O Relora avisa sobre ações que podem prejudicar a sua relação.",
      "features.screenshot.title": "Qualquer app, qualquer captura",
      "features.screenshot.desc": "WhatsApp, Instagram, Tinder, Snapchat — analise capturas de qualquer aplicação de mensagens.",
      "features.private.title": "Totalmente privado",
      "features.private.desc": "Todo o processamento de IA ocorre no seu dispositivo. As suas conversas nunca são transmitidas.",
      "how.label": "How it works",
      "how.title": "Análise completa em 3 passos",
      "how.desc": "Simples e intuitivo — insights profundos em segundos.",
      "how.step1.title": "Tire uma captura de ecrã",
      "how.step1.desc": "Capture a conversa que quer analisar. Pode enviar várias imagens ao mesmo tempo.",
      "how.step2.title": "Defina o contexto",
      "how.step2.desc": "Escolha o tipo de relação, objetivo e situação no menu. Acrescente notas se necessário.",
      "how.step3.title": "A IA analisa",
      "how.step3.desc": "Resultados estruturados: psicologia, nível de interesse, opções de resposta e riscos — tudo processado localmente.",
      "privacy_section.title": "Os seus dados pertencem a si",
      "privacy_section.desc": "O Relora não usa qualquer servidor. Cada processo de IA corre inteiramente no seu iPhone.",
      "privacy_section.ondevice.title": "IA no dispositivo",
      "privacy_section.ondevice.desc": "Todo o processamento de IA corre no seu iPhone",
      "privacy_section.nodata.title": "Sem transmissão de dados",
      "privacy_section.nodata.desc": "Capturas e conversas nunca são enviadas para servidores externos",
      "privacy_section.delete.title": "Eliminação total",
      "privacy_section.delete.desc": "Desinstale a app e todos os seus dados desaparecem",
      "pricing.label": "Pricing",
      "pricing.title": "Preços simples e transparentes",
      "pricing.desc": "Comece de graça, mude para Premium quando quiser.",
      "pricing.free.name": "Gratuito",
      "pricing.free.price": "¥0",
      "pricing.free.f1": "3 análises por dia",
      "pricing.free.f2": "Análise psicológica básica",
      "pricing.free.f3": "Sugestões de resposta",
      "pricing.free.f4": "Privacidade totalmente protegida",
      "pricing.free.cta": "Começar de graça",
      "pricing.premium.badge": "Recomendado",
      "pricing.premium.name": "Premium",
      "pricing.premium.price_html": '¥980<span>/mês</span>',
      "pricing.premium.f1": "Análises ilimitadas",
      "pricing.premium.f2": "Análise psicológica aprofundada e estratégica",
      "pricing.premium.f3": "Memória por pessoa e personalização",
      "pricing.premium.f4": "Histórico e análise de tendências",
      "pricing.premium.f5": "Privacidade totalmente protegida",
      "pricing.premium.cta": "Ir para Premium",
      "cta.title": "Deixe a IA ajudá-lo no amor",
      "cta.desc": "O Relora apoia as suas decisões.",
      "cta.button": "Descarregar na App Store",
      "footer.privacy": "Política de Privacidade",
      "footer.terms": "Termos de Serviço",
      "footer.contact": "Contacto",
      "privacy.meta.title": "Política de Privacidade — Relora",
      "privacy.title": "Política de Privacidade",
      "privacy.date": "Última atualização: 5 de abril de 2026",
      "privacy.intro": "O Relora (doravante «o App») foi desenvolvido tendo a privacidade do utilizador como prioridade máxima. Esta política descreve como as informações são tratadas no âmbito do App.",
      "privacy.h1": "1. Princípios Fundamentais",
      "privacy.p1": "O App funciona inteiramente no dispositivo. Os seus dados nunca são transmitidos a servidores externos. Todo o processamento de IA é realizado no seu dispositivo.",
      "privacy.h2": "2. Informações Processadas",
      "privacy.p2": "As seguintes informações podem ser processadas pelo App no seu dispositivo. Todas são armazenadas exclusivamente no seu dispositivo.",
      "privacy.p2.li1": "Imagens de capturas de ecrã que você forneça",
      "privacy.p2.li2": "Informações de texto que você introduza (notas complementares, etc.)",
      "privacy.p2.li3": "Resultados da análise de IA",
      "privacy.p2.li4": "Informações sobre compras dentro do app (processadas através da Apple)",
      "privacy.h3": "3. Finalidade da Utilização",
      "privacy.p3": "As informações acima são utilizadas exclusivamente para o processamento de análise de IA no dispositivo.",
      "privacy.h4": "4. Divulgação a Terceiros",
      "privacy.p4": "O App não partilha as suas informações com terceiros. Nenhum dado é transmitido a servidores externos.",
      "privacy.h5": "5. Armazenamento de Dados",
      "privacy.p5": "Todos os dados são armazenados exclusivamente no seu dispositivo. Não é realizada nenhuma cópia de segurança na nuvem.",
      "privacy.h6": "6. Eliminação de Dados",
      "privacy.p6": "Ao eliminar o App, todos os dados associados ao mesmo são removidos. Também é possível eliminar dados individuais nas definições do App.",
      "privacy.h7": "7. Privacidade na App Store",
      "privacy.p7.li1": "Data Not Collected: este app não recolhe dados dos utilizadores",
      "privacy.p7.li2": "Data Not Linked to You: os dados não estão associados à sua identidade",
      "privacy.h8": "8. Privacidade de Menores",
      "privacy.p8": "O App destina-se a utilizadores com 17 anos ou mais. Não recolhemos intencionalmente informações de menores de 17 anos.",
      "privacy.h9": "9. Alterações à Política",
      "privacy.p9": "Esta política pode ser alterada sem aviso prévio. Quaisquer alterações serão refletidas nesta página.",
      "privacy.h10": "10. Contacto",
      "privacy.p10": "Para questões relacionadas com a privacidade, entre em contacto connosco através do endereço indicado abaixo.",
      "privacy.nav.home": "Início",
      "privacy.nav.terms": "Termos de Utilização",
      "terms.meta.title": "Termos de Serviço — Relora",
      "terms.title": "Termos de Serviço",
      "terms.date": "Última atualização: 5 de abril de 2026",
      "terms.intro": "Os presentes Termos de Serviço (doravante «Termos») regem a utilização do Relora (doravante «Aplicação»). Leia atentamente estes Termos antes de utilizar a Aplicação.",
      "terms.h1": "1. Descrição do serviço",
      "terms.p1a": "A Aplicação é um serviço de informação de referência que utiliza inteligência artificial para analisar capturas de ecrã de conversas e fornece análises psicológicas das conversas e sugestões de resposta.",
      "terms.p1b": "As informações fornecidas pela Aplicação são informações de referência gerais baseadas em tendências identificadas pela IA e não constituem aconselhamento ou assistência profissional.",
      "terms.h2": "2. Limitação de responsabilidade",
      "terms.p2.li1": "Não garantimos a exatidão, integridade ou utilidade dos resultados de análise da Aplicação",
      "terms.p2.li2": "O desenvolvedor não assume qualquer responsabilidade pelas consequências de ações tomadas com base na utilização da Aplicação",
      "terms.p2.li3": "Todas as decisões finais relativas a mensagens enviadas ou ações tomadas são da exclusiva responsabilidade do utilizador",
      "terms.p2.li4": "A Aplicação não substitui o aconselhamento profissional em matéria de relacionamentos amorosos ou interpessoais",
      "terms.h3": "3. Condições de utilização",
      "terms.p3.li1": "A Aplicação destina-se a utilizadores com 17 anos ou mais",
      "terms.p3.li2": "A Aplicação não pode ser utilizada para fins ilegais",
      "terms.p3.li3": "É estritamente proibida a utilização da Aplicação para fins de stalking, assédio ou qualquer outro propósito que cause dano a terceiros",
      "terms.h4": "4. Faturação",
      "terms.p4.li1": "A Aplicação oferece compras integradas (subscrições)",
      "terms.p4.li2": "Os pagamentos são processados através da Apple Inc.",
      "terms.p4.li3": "As subscrições renovam-se automaticamente. A menos que sejam canceladas pelo menos 24 horas antes da data de renovação, a subscrição será automaticamente renovada",
      "terms.p4.li4": "As subscrições podem ser geridas e canceladas através da aplicação Definições do iOS",
      "terms.h5": "5. Propriedade intelectual",
      "terms.p5": "Todos os direitos de propriedade intelectual relativos ao design, código e conteúdo da Aplicação pertencem ao desenvolvedor.",
      "terms.h6": "6. Alteração e encerramento do serviço",
      "terms.p6": "O desenvolvedor reserva-se o direito de alterar as funcionalidades da Aplicação ou de encerrar o serviço a qualquer momento sem aviso prévio.",
      "terms.h7": "7. Alterações aos presentes Termos",
      "terms.p7": "Os presentes Termos podem ser atualizados sem aviso prévio. Os Termos alterados entram em vigor no momento da sua publicação nesta página.",
      "terms.h8": "8. Lei aplicável e tribunal competente",
      "terms.p8": "Os presentes Termos são regidos pela legislação japonesa. Qualquer litígio relacionado com os presentes Termos ficará sujeito à jurisdição exclusiva do Tribunal Distrital de Tóquio como tribunal de primeira instância.",
      "terms.h9": "9. Contacto",
      "terms.p9": "Para quaisquer questões relativas aos presentes Termos, contacte-nos através do endereço indicado abaixo.",
      "terms.nav.home": "Início",
      "terms.nav.privacy": "Política de privacidade"
    }
  };

  // ── i18n engine ──

  function detect() {
    var saved = localStorage.getItem('relora_lang');
    if (saved && T[saved]) return saved;
    var nav = (navigator.language || '').slice(0, 2);
    return T[nav] ? nav : 'en';
  }

  function apply(lang) {
    var dict = T[lang];
    if (!dict) return;

    // text nodes
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n');
      if (dict[key] != null) el.textContent = dict[key];
    });

    // html nodes (innerHTML)
    document.querySelectorAll('[data-i18n-html]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-html');
      if (dict[key] != null) el.innerHTML = dict[key];
    });

    // title & meta
    if (dict['meta.title']) document.title = dict['meta.title'];
    var metaDesc = document.querySelector('meta[name="description"]');
    if (metaDesc && dict['meta.description']) metaDesc.setAttribute('content', dict['meta.description']);

    // page-specific title
    document.querySelectorAll('[data-i18n-title]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-title');
      if (dict[key]) document.title = dict[key];
    });

    // data-badge attribute (e.g. pricing card badge)
    document.querySelectorAll('[data-i18n-badge]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-badge');
      if (dict[key]) el.setAttribute('data-badge', dict[key]);
    });

    document.documentElement.lang = lang;
    localStorage.setItem('relora_lang', lang);

    // update selector
    var sel = document.getElementById('lang-select');
    if (sel) sel.value = lang;
  }

  function createSelector() {
    var sel = document.createElement('select');
    sel.id = 'lang-select';
    sel.setAttribute('aria-label', 'Language');
    Object.keys(LANGS).forEach(function (code) {
      var opt = document.createElement('option');
      opt.value = code;
      opt.textContent = LANGS[code];
      sel.appendChild(opt);
    });

    sel.style.cssText = 'appearance:none;-webkit-appearance:none;background:transparent;border:1px solid rgba(28,28,28,0.2);border-radius:6px;padding:6px 28px 6px 10px;font-size:13px;font-family:inherit;color:inherit;cursor:pointer;background-image:url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'12\' height=\'12\' viewBox=\'0 0 12 12\'%3E%3Cpath d=\'M3 4.5l3 3 3-3\' fill=\'none\' stroke=\'%235f5f5d\' stroke-width=\'1.5\' stroke-linecap=\'round\' stroke-linejoin=\'round\'/%3E%3C/svg%3E");background-repeat:no-repeat;background-position:right 8px center;';

    sel.addEventListener('change', function () {
      apply(sel.value);
    });
    return sel;
  }

  function init() {
    // inject selector into nav
    var nav = document.querySelector('.nav');
    if (nav) {
      var sel = createSelector();
      // insert into .nav-right before CTA, or append to nav
      var navRight = nav.querySelector('.nav-right');
      if (navRight) {
        navRight.insertBefore(sel, navRight.firstChild);
      } else {
        nav.appendChild(sel);
      }
    }

    var lang = detect();
    apply(lang);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
